# Generated by Django 4.2.14 on 2024-07-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=1000)),
                ('name', models.TextField(max_length=20)),
            ],
            options={
                'db_table': 'Recipe',
            },
        ),
    ]
